language: ruby
cache: bundler
sudo: false
rvm:
 - 2.4
script:
 - bundle exec htmlproofer ./_site
 - bundle exec jekyll build
 - grep post-title         _site/index.html
 - grep pagination-item    _site/index.html
 - grep 404                _site/404.html
